### ISSUE TITLE
쿠키 사용 관련 패키지

### ISSUE THREAD

**Issue by ywj3493** [Co-Laon/claon-app#127]
## Describe
쿠키는 브라우저마다 처리가 조금씩 다르기 때문에, climbingweb 프로젝트에서 react-cookie를 사용할 지, climbingapp 프로젝트에서 react-native-cookie를 선택 해야 할 것 같다.

## (Optional) Solution
- 앱에서 앱 종료시에도 로그인을 유지해야하는 필요성이 있다면 react-native-cookie를 사용하는 것이 좋을 듯 하다.
- climbingweb 에서는 불필요한 패키지 설치를 피하기 위해 크롬에서 동작하는 쿠키 관련 mock 함수를 만들어 사용하는 것이 좋을 듯 하다.

**Comment by qowlsdn8007** [comment]
@ywj3493  
- 앱에는 토큰값 자체만 저장하면되니 asyncStorage를 통해 토큰을 보관  
- 이를 로그인할 때 꺼내서 브릿지  함수를 사용해 웹뷰에 전달하고 웹뷰가 토큰을 쿠키에 넣고 다루어야할듯 합니다.
- 고로 react-cookie를 사용해서 웹에서 관리만 하면 될듯..?? 합니다
