### ISSUE TITLE
검색 버그

### ISSUE THREAD

**Issue by qowlsdn8007** [Co-Laon/claon-app#171]
## Outline of bug
검색 시 에러 발생

## How to encounter/reproduce bug
 실제 있는 wooch 라는 사용자를 검색하려 시도했더니 에러 발생
 이미지 관련 버그가 있는 듯

## Expected behavior or result
![검색버그](https://user-images.githubusercontent.com/33804074/209542427-56fc1cab-5cbe-483f-8788-68c1bc5a93b4.gif)

## Actual result
사용자가 검색 결과에 노출되어야함

**Comment by ywj3493** [comment]
해당 문제는 UserResult 컴포넌트에 사용된 Image에서 문제가 된 것 같습니다. ProfileImage 컴포넌트로 변경하면 해결 될 것 같으니 제가 변경 하겠습니다.
