### ISSUE TITLE
[CSS] 가입 이용약관

### ISSUE THREAD

**Issue by als95** [Co-Laon/claon-app#195]
## Describe
가입 이용약관 페이지 CSS 적용

- target #가입_이용약관

**Comment by qowlsdn8007** [comment]
@als95  @ChanghyukWoo  이용약관 컨텐츠가 필요합니다. 현재는 빈 화면

**Comment by als95** [comment]
> @als95 @ChanghyukWoo 이용약관 컨텐츠가 필요합니다. 현재는 빈 화면

@qowlsdn8007 옙! 해당 이슈는 TODO로 남겨둡시다.

**Comment by qowlsdn8007** [comment]
@als95  개인정보처리방침, 이용약관 등이 구글 oauth production 등록 등에도 사용이 되어서 이제는 진행해야할 듯 합니다
