### ISSUE TITLE
[CSS] 가입 인스타그램 로그인

### ISSUE THREAD

**Issue by als95** [Co-Laon/claon-app#198]
## Describe
가입 인스타그램 로그인 페이지 CSS 적용

- target #가입_인스타그램_로그인

**Comment by qowlsdn8007** [comment]
인스타그램 가입???

**Comment by als95** [comment]
> 인스타그램 가입???

@qowlsdn8007 회원가입 과정에 있는 인스타그램 계정 입력을 의미합니다.
가입_인스타그램_로그인 화면을 참고해주세요.
