### ISSUE TITLE
[Bug] 검색 화면 자동 검색

### ISSUE THREAD

**Issue by als95** [Co-Laon/claon-app#256]
## Outline of bug
검색이 자동으로 이루어지는 현상

## How to encounter/reproduce bug
검색이 자동으로 이루어지는 현상

## Expected behavior or result
사용자가 검색어를 입력 후 확인을 눌렀을 때, 검색 결과가 조회될 수 있도록 수정

## Screenshots or Video
A screenshot or video of the bug

**Comment by ywj3493** [comment]
> 이부분 저는 현재처럼 디바운싱 줘서 단어 입력 시 이름과 겹치는 암장, 라온이 출력되는게 더 자연스러운거같아요, 사용자가 찾기도 더 편한거 같기두 하구요!
> 
> @ywj3493 추가적인 의견 부탁드려요

@qowlsdn8007 죄송합니다.. 지금 봤네요. @als95 기획에서 딱히 확인 버튼이 보이지 않아서 디바운싱으로 구현했었습니다. 지금처럼 디바운싱으로 구현하지 않으려면 글자 입력에 따른 하위 selectbox 또는 확인 버튼 등 추가적인 기획이 필요할 것 같습니다.

**Comment by qowlsdn8007** [comment]
@als95 확인부탁드립니다
